---
title: "simulation_functions"
author: "Doudou Carol Cao"
date: "2023-06-14"
output: html_document
---
# 7. Simulating Three Commingling Conditions 
## Install and load necessary packages
```{r}
install.packages("tidyverse", repos = "https://cran.r-project.org/")
install.packages("viridis", repos = "https://cran.r-project.org/")
install.packages("terra", repos = "https://cran.r-project.org/")
install.packages("gridExtra", repos = "https://cran.r-project.org/") 

library(viridis)
library(tidyverse)
library(terra)
library(gridExtra)
library(scales)
```
## 7.1. Function for calculating and comparing the aggregated and conventional indices
### 7.1.1 cBI vs. aBI
```{r}
simFun_bi <- function(n1,n2,mean.hml,sd.hml,sd.bi,mean.bi,nsim)
{
  est.bi  <- numeric(length=nsim) #just a placeholder vector for storing estimates
  for (i in 1:nsim) #main simulation loop
  {
    #Simulate paired individuals
    hml.paired  <- rnorm(n1/2,mean=mean.hml,sd=sd.hml)
    bi.paired  <- rnorm(n1/2,mean=mean.bi,sd=sd.bi)
    rml.paired  <- hml.paired * bi.paired
    #Simulate unpaired individuals
    hml.unpaired  <- rnorm(n2/2,mean=mean.hml,sd=sd.hml) 
    #Simulate half the femur as normal
    rml.unpaired  <- rnorm(n2/2,mean=mean.hml,sd=sd.hml) * rnorm(n2/2,mean=mean.bi,sd=sd.bi) #Simulate another set of femurs but store only their corresponding Tibia after drawing other crural index values
    #Combine
    hml <- c(hml.paired,hml.unpaired)
    rml <- c(rml.paired,rml.unpaired)
    #Estimate
    est.bi[i]  <- mean(rml)/mean(hml)
  }
  return(list(true.bi=mean.bi,est.bi=est.bi,error=est.bi-mean.bi))
}
```

### 7.1.2 cCI vs. aCI
```{r}
simFun_ci <- function(n1,n2,mean.fbl,sd.fbl,sd.ci,mean.ci,nsim)
{
  est.ci  <- numeric(length=nsim) #just a placeholder vector for storing estimates
  for (i in 1:nsim) #main simulaion loop
  {
    #Simulate paired individuals
    fbl.paired  <- rnorm(n1/2,mean=mean.fbl,sd=sd.fbl)
    ci.paired  <- rnorm(n1/2,mean=mean.ci,sd=sd.ci)
    tml.paired  <- fbl.paired * ci.paired
    #Simulate unpaired individuals
    fbl.unpaired  <- rnorm(n2/2,mean=mean.fbl,sd=sd.fbl) 
    #Simulate half the femur as normal
    tml.unpaired  <- rnorm(n2/2,mean=mean.fbl,sd=sd.fbl) * rnorm(n2/2,mean=mean.ci,sd=sd.ci) #Simulate another set of femurs but store only their corresponding Tibia after drawing other crural index values
    #Combine
    fbl <- c(fbl.paired,fbl.unpaired)
    tml <- c(tml.paired,tml.unpaired)
    #Estimate
    est.ci[i]  <- mean(tml)/mean(fbl)
  }
  return(list(true.ci=mean.ci,est.ci=est.ci,error=est.ci-mean.ci)) # 
}
```

## 7.2. Function for simulating the sample size (n), commingling (c) and variation (v)
### 7.2.1. Simulate the BI
```{r}
# Create grid of parameter combinations to simulate
n <- seq(10, 300, length.out = 30) # Sample size
c <- seq(0, 1, length.out = 30)    # Commingling Degree
v <- c(0.01, 0.02, 0.08) # Within-group Variation in the Brachial index
parm <- expand.grid(n, c, v)

# Modify simulate function to run simulation 10000 times
simulate <- function(parms, n_sims = 10000) {
  # Extract parameters from parms
  n <- parms[1]
  c <- parms[2]
  v <- parms[3]
  
  # Round n to the nearest even number
  n <- round(n/2) * 2
  
  # Initialize variables to store results
  error_set <- numeric(n_sims)
  
  # Run simulations
  for (i in 1:n_sims) {
    # Call the simFun_ci function with the specified parameters
    sim_result <- simFun_bi(n1 = round(n*(1-c)), n2 = round(n*c), mean.hml=308.73,sd.hml=13.24, sd.bi = v, mean.bi = 0.7597, nsim = 1)
    
    # Compute error
    error <- abs(sim_result$error)
    
    # Store results
    error_set[i] <- sim_result$error
  }
  
 # Compute summary statistics of the errors
   mean_abs_error <- abs(mean(error_set)) #  the absolute value of the mean
   median_abs_error <- abs(median(error_set)) # absolute value of the median_error
   percentile_75 <- abs(quantile(error_set, probs = 0.75, na.rm = TRUE))# Compute the 75th percentile of the errors
   
   # Compute values that are greater than 0.02
    abs_error_count <- sum(abs(error_set) > 0.02, na.rm = TRUE) # the number of errors in the error_set that have an absolute value greater than 0.02, excluding any NA values.
    # the proportion of simulations where the absolute value of the median_error is greater than 0.02
    prop_large_error <- abs_error_count / sum(!is.na(error_set))

   # Create data frame with results and parameters
   results_df_bi <- data.frame(n = n, c = c, v = v, 
                              mean_abs_error = mean_abs_error,median_abs_error = median_abs_error, percentile_75=percentile_75, 
                              abs_error_count = abs_error_count, prop_large_error = prop_large_error)

  return(results_df_bi)
}

# Run simulation and store results in a data frame
set.seed(123) # set seed for reproducibility
results_bi <- replicate(1, apply(parm, 1, simulate), simplify = FALSE)
results_df_bi <- bind_rows(results_bi)
```

### 7.2.1. Simulate the CI
```{r}
# Create grid of parameter combinations to simulate
n <- seq(10, 300, length.out = 30) # Sample size
c <- seq(0, 1, length.out = 30)    # Commingling Degree
v <- c(0.01, 0.02, 0.05) # Within-group Variation in the Crural index
parm <- expand.grid(n, c, v)

# Modify simulate function to run simulation 10000 times
simulate <- function(parms, n_sims = 10000) {
  # Extract parameters from parms
  n <- parms[1]
  c <- parms[2]
  v <- parms[3]
  
  # Round n to the nearest even number
  n <- round(n/2) * 2
  
  # Initialize variables to store results
  error_set <- numeric(n_sims)
  
  # Run simulations
  for (i in 1:n_sims) {
    # Call the simFun_ci function with the specified parameters
    sim_result <- simFun_ci(n1 = round(n*(1-c)), n2 = round(n*c), mean.fbl=426.64,sd.fbl=26.07, sd.ci = v, mean.ci = 0.8348, nsim = 1)
    
    # Compute error
    error <- abs(sim_result$error)
    
    # Store results
    error_set[i] <- sim_result$error
  }
  
   # Compute summary statistics of the errors
   mean_abs_error <- abs(mean(error_set)) #  the absolute value of the mean
   median_abs_error <- abs(median(error_set)) # absolute value of the median_error
   percentile_75 <- abs(quantile(error_set, probs = 0.75, na.rm = TRUE))# Compute the 75th percentile of the errors
   
   # Compute values that are greater than 0.02
    abs_error_count <- sum(abs(error_set) > 0.02, na.rm = TRUE) # the number of errors in the error_set that have an absolute value greater than 0.02, excluding any NA values.
    # the proportion of simulations where the absolute value of the median_error is greater than 0.02
    prop_large_error <- abs_error_count / sum(!is.na(error_set))
    

   # Create data frame with results and parameters
   results_df_ci <- data.frame(n = n, c = c, v = v, 
                              mean_abs_error = mean_abs_error,median_abs_error = median_abs_error, percentile_75=percentile_75, 
                              abs_error_count = abs_error_count, prop_large_error = prop_large_error)

  return(results_df_ci)
}

# Run simulation and store results in a data frame
set.seed(123) # set seed for reproducibility
results_ci <- replicate(1, apply(parm, 1, simulate), simplify = FALSE)
results_df_ci <- bind_rows(results_ci)
```

